#!/bin/bash
#  Login To Instance x with SSH 
#
# helper functions
function error_in_use() {
    #echo "from error-function echoing parameter 1 \"$(basename $1)\""
    echo "----------------------------------------------"
    echo "$(basename $0) logs you to a (AWS) instance using ssh."
    echo " ";
    echo "usage: "
    echo " ";
    echo "    $(basename $0)  login-key-file.pem  csuser/ubuntu" ;
    echo " ";
    echo "- login-key-file.pem is the name of the file containing the RSA login key to access the instance."
    echo "  Use the key Tab to easily reach the file within a directory, see examples below."
    echo " ";	 
    echo "- Examples:";
    echo "  $(basename $0) gc_run02_data/outputs/login-keys/login-key-instance017.pem  csuser";
    echo "  $(basename $0) gc_run02_data/outputs/login-keys/login-key-instance017.pem  ubuntu";
    echo " ";	 
    echo "- NB: the following domain name is assumed and used to log you in with the user specified ";
    echo "  csuser@instance017.cloud-span.aws.york.ac.uk";
}

loginKeyFile=$1
user=$2
domain="cloud-span.aws.york.ac.uk"
machine="to define"
### start:
case $# in
    2) # two parameters given as expected. Check the login key file specified exists.
	if [ -f $loginKeyFile ]; then
	    # file exists. Check the user given is csuser or ubuntu
	    if [ $user == "csuser"  -o $user == "ubuntu" ]; then
		# unpack machine name from the login key file name which has the form:
		# gc_run02_data/outputs/login-keys/login-key-instance017.pem 
		machine=${loginKeyFile%.pem}    # get rid of .pem at the end
		machine=${machine/#*-/}		# from the beginning/prefix (#), everything (*) up to -, replace it / with nothing.
	    else
		echo 
		echo "Error: user must be \"csuser\"  or \"ubuntu\" (with no quotes)."
		error_in_use
		exit 2
	    fi
	else
	    echo 
	    echo "Error: login key file $loginKeyFile DOES NOT EXIST."
	    error_in_use
	    exit 2
	fi
	echo "logging thus: ssh -i $loginKeyFile $user@$machine.$domain"
	ssh -i $loginKeyFile $user@$machine.$domain
	exit 0;;
    *) error_in_use "$1"
       exit 2;;
esac
