#!/bin/bash
# rlgn  logins into a remote machine
#
# helper functions
function error_in_use() {
    #echo "from error-function echoing parameter 1 \"$(basename $1)\""
    echo "$(basename $0) logins into a remote machine using ssh."
    echo " ";
    echo "usage: "
    echo " ";
    echo "    $(basename $0)  [login_info_file]" ;
    echo " ";
    echo "- login_info_file is the name of the file containing (space-separated or in different lines):"
    echo "  username  machine-domain-name  loging-key-file-name";
    echo " ";	 
    echo "- if no login_info_file is specified, the file \"logininfo\" must exist in the";
    echo "  current directory";    
}

### start:
case $# in
    0|1) if [ $# -eq 0 ]; then
	     # the login info file is in current directory
	     if [ -f ./logininfo ]; then
		 logindetails=( `cat ./logininfo` )
	     else
		 echo "Error: login info file \"logininfo\" DOES NOT EXIST in current directory."
		 error_in_use
		 exit 2
	     fi
	 elif [ -f $1 ]; then
	     # login details file specified by caller
	     logindetails=( `cat $1` )
	 else
	     echo "Error: login credentials file \"$1\" DOES NOT EXIST."
	     error_in_use
	     exit 2
	 fi
	 # unpack login details
	 username=${logindetails[0]}
	 machinedomainname=${logindetails[1]}
	 loginkeyfile=${logindetails[2]}

	 echo "login in thus: ssh -i $loginkeyfile $username@$machinedomainname"
	 ssh -i $loginkeyfile $username@$machinedomainname
	 exit 0;;
    *) error_in_use "$1"
       exit 2;;
esac
